export const classData = [
  {
    _id: "1",
    title: "Introduction to Algebra",
    description: "Learn the basics of algebra including variables, equations, and functions.",
    instructor: "John Doe",
    duration: "4 weeks",
    price: "$100",
    level: "Beginner",
    status: "Active",
  },
  {
    _id: "2",
    title: "Fundamentals of Geometry",
    description: "Explore shapes, angles, and geometric proofs with interactive lessons.",
    instructor: "Jane Smith",
    duration: "5 weeks",
    price: "$120",
    level: "Beginner",
    status: "Active",
  },
  {
    _id: "3",
    title: "Advanced Calculus",
    description: "Master differentiation, integration, and real-world calculus applications.",
    instructor: "Robert Brown",
    duration: "8 weeks",
    price: "$200",
    level: "Advanced",
    status: "Active",
  },
  {
    _id: "4",
    title: "Statistics for Data Science",
    description: "Learn how to collect, analyze, and interpret data for decision-making.",
    instructor: "Emily Johnson",
    duration: "6 weeks",
    price: "$150",
    level: "Intermediate",
    status: "Active",
  },
  {
    _id: "5",
    title: "Trigonometry Essentials",
    description: "Understand sine, cosine, tangent, and their applications in real life.",
    instructor: "Michael Lee",
    duration: "5 weeks",
    price: "$130",
    level: "Intermediate",
    status: "Inactive",
  },
  {
    _id: "6",
    title: "Linear Algebra Mastery",
    description: "Dive into matrices, vectors, and linear transformations in depth.",
    instructor: "Sarah Green",
    duration: "7 weeks",
    price: "$180",
    level: "Advanced",
    status: "Active",
  },
  {
    _id: "7",
    title: "Discrete Mathematics",
    description: "Learn about logic, sets, combinatorics, and graph theory fundamentals.",
    instructor: "David Wilson",
    duration: "6 weeks",
    price: "$160",
    level: "Intermediate",
    status: "Active",
  },
  {
    _id: "8",
    title: "Probability Theory Basics",
    description: "Understand probability concepts and their applications in daily life.",
    instructor: "Laura Adams",
    duration: "4 weeks",
    price: "$110",
    level: "Beginner",
    status: "Active",
  },
  {
    _id: "9",
    title: "Applied Mathematics for Engineers",
    description: "Focus on practical math techniques used in engineering fields.",
    instructor: "Thomas Carter",
    duration: "9 weeks",
    price: "$220",
    level: "Advanced",
    status: "Active",
  },
  {
    _id: "10",
    title: "Pre-Calculus Preparation",
    description: "Bridge the gap between algebra and calculus with essential concepts.",
    instructor: "Sophia Martinez",
    duration: "6 weeks",
    price: "$140",
    level: "Intermediate",
    status: "Active",
  }
];
