export const students = [
  {
    id: 1,
    title: null,
    first_name: "Arthur",
    last_name: "Hoskins",
    email: "arthur_hoskins@example.com",
    mobile: null,
    phone: null,
    street: "12 Helmet Row",
    state: null,
    town: "London",
    country: "United Kingdom (GB)",
    postcode: "EC1V 3QJ",
    latitude: "51.5249280000000027",
    longitude: "-0.0944689940000000",
    date_created: "2019-11-24T16:11:48.312507Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 3,
      first_name: "Jamie",
      last_name: "Hoskins",
      email: "jamie_hoskins@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/3/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2019-11-24T16:11:48.312507Z",
    calendar_colour: "Khaki",
    labels: [],
    extra_attrs: []
  },
  {
    id: 2,
    title: null,
    first_name: "Sophia",
    last_name: "Brown",
    email: "sophia_brown@example.com",
    mobile: "07123456789",
    phone: null,
    street: "45 Queen Street",
    state: null,
    town: "Manchester",
    country: "United Kingdom (GB)",
    postcode: "M1 2AD",
    latitude: "53.479489",
    longitude: "-2.245115",
    date_created: "2020-01-14T10:25:12.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 4,
      first_name: "Olivia",
      last_name: "Brown",
      email: "olivia_brown@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/4/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2020-01-14T10:25:12.000Z",
    calendar_colour: "SkyBlue",
    labels: [],
    extra_attrs: []
  },
  {
    id: 3,
    title: null,
    first_name: "Liam",
    last_name: "Johnson",
    email: "liam_johnson@example.com",
    mobile: "07987654321",
    phone: null,
    street: "78 Baker Street",
    state: null,
    town: "London",
    country: "United Kingdom (GB)",
    postcode: "W1U 6RF",
    latitude: "51.520534",
    longitude: "-0.156986",
    date_created: "2021-05-10T09:45:22.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 5,
      first_name: "Noah",
      last_name: "Johnson",
      email: "noah_johnson@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/5/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2021-05-10T09:45:22.000Z",
    calendar_colour: "LightGreen",
    labels: [],
    extra_attrs: []
  },
  {
    id: 4,
    title: null,
    first_name: "Emma",
    last_name: "Davis",
    email: "emma_davis@example.com",
    mobile: "07555555555",
    phone: null,
    street: "32 River Road",
    state: null,
    town: "Liverpool",
    country: "United Kingdom (GB)",
    postcode: "L3 5RF",
    latitude: "53.408371",
    longitude: "-2.991573",
    date_created: "2022-03-02T14:12:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 6,
      first_name: "Ella",
      last_name: "Davis",
      email: "ella_davis@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/6/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2022-03-02T14:12:00.000Z",
    calendar_colour: "Coral",
    labels: [],
    extra_attrs: []
  },
  {
    id: 5,
    title: null,
    first_name: "Oliver",
    last_name: "Miller",
    email: "oliver_miller@example.com",
    mobile: "07888888888",
    phone: null,
    street: "9 Elm Street",
    state: null,
    town: "Birmingham",
    country: "United Kingdom (GB)",
    postcode: "B1 1AA",
    latitude: "52.486243",
    longitude: "-1.890401",
    date_created: "2022-09-10T08:20:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 7,
      first_name: "Amelia",
      last_name: "Miller",
      email: "amelia_miller@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/7/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2022-09-10T08:20:00.000Z",
    calendar_colour: "Plum",
    labels: [],
    extra_attrs: []
  },
  {
    id: 6,
    title: null,
    first_name: "Ava",
    last_name: "Wilson",
    email: "ava_wilson@example.com",
    mobile: null,
    phone: null,
    street: "23 Oak Avenue",
    state: null,
    town: "Leeds",
    country: "United Kingdom (GB)",
    postcode: "LS1 2AB",
    latitude: "53.800755",
    longitude: "-1.549077",
    date_created: "2023-01-12T11:00:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 8,
      first_name: "Grace",
      last_name: "Wilson",
      email: "grace_wilson@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/8/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2023-01-12T11:00:00.000Z",
    calendar_colour: "LightCoral",
    labels: [],
    extra_attrs: []
  },
  {
    id: 7,
    title: null,
    first_name: "Lucas",
    last_name: "Taylor",
    email: "lucas_taylor@example.com",
    mobile: "07222222222",
    phone: null,
    street: "5 Bridge Street",
    state: null,
    town: "Bristol",
    country: "United Kingdom (GB)",
    postcode: "BS1 6XY",
    latitude: "51.454514",
    longitude: "-2.587910",
    date_created: "2023-04-19T09:10:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 9,
      first_name: "Henry",
      last_name: "Taylor",
      email: "henry_taylor@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/9/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2023-04-19T09:10:00.000Z",
    calendar_colour: "Tomato",
    labels: [],
    extra_attrs: []
  },
  {
    id: 8,
    title: null,
    first_name: "Mia",
    last_name: "Anderson",
    email: "mia_anderson@example.com",
    mobile: "07333333333",
    phone: null,
    street: "17 Park Road",
    state: null,
    town: "Nottingham",
    country: "United Kingdom (GB)",
    postcode: "NG1 5FX",
    latitude: "52.954783",
    longitude: "-1.158109",
    date_created: "2023-06-15T10:30:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 10,
      first_name: "Isla",
      last_name: "Anderson",
      email: "isla_anderson@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/10/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2023-06-15T10:30:00.000Z",
    calendar_colour: "Orchid",
    labels: [],
    extra_attrs: []
  },
  {
    id: 9,
    title: null,
    first_name: "Ethan",
    last_name: "Moore",
    email: "ethan_moore@example.com",
    mobile: "07444444444",
    phone: null,
    street: "26 Lake View",
    state: null,
    town: "Cardiff",
    country: "United Kingdom (GB)",
    postcode: "CF10 1EP",
    latitude: "51.481583",
    longitude: "-3.179090",
    date_created: "2023-09-01T15:00:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 11,
      first_name: "Charlotte",
      last_name: "Moore",
      email: "charlotte_moore@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/11/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2023-09-01T15:00:00.000Z",
    calendar_colour: "LightSeaGreen",
    labels: [],
    extra_attrs: []
  },
  {
    id: 10,
    title: null,
    first_name: "Ella",
    last_name: "White",
    email: "ella_white@example.com",
    mobile: null,
    phone: null,
    street: "9 Garden Lane",
    state: null,
    town: "Oxford",
    country: "United Kingdom (GB)",
    postcode: "OX1 1AB",
    latitude: "51.752022",
    longitude: "-1.257677",
    date_created: "2024-02-28T12:40:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 12,
      first_name: "Harper",
      last_name: "White",
      email: "harper_white@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/12/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2024-02-28T12:40:00.000Z",
    calendar_colour: "GoldenRod",
    labels: [],
    extra_attrs: []
  },
  {
    id: 11,
    title: null,
    first_name: "James",
    last_name: "Hall",
    email: "james_hall@example.com",
    mobile: "07999999999",
    phone: null,
    street: "3 Church Road",
    state: null,
    town: "Cambridge",
    country: "United Kingdom (GB)",
    postcode: "CB1 1PT",
    latitude: "52.205337",
    longitude: "0.121817",
    date_created: "2024-08-05T09:00:00.000Z",
    timezone: null,
    default_rate: null,
    paying_client: {
      id: 13,
      first_name: "Lily",
      last_name: "Hall",
      email: "lily_hall@example.com",
      url: "https://secure.tutorcruncher.com/api/clients/13/"
    },
    associated_clients: [],
    academic_year: null,
    last_updated: "2024-08-05T09:00:00.000Z",
    calendar_colour: "Teal",
    labels: [],
    extra_attrs: []
  }
]
